### ISSUE TITLE
云图热点跳转链接的逻辑

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#847]
**测试环境：**
>Web端地址：
>
[http://z-tron.cn/play/demo/demoDemand.html?title=wcdbcs&k=E1yzuXJrg&videojjhost=videojj.com](http://z-tron.cn/play/demo/demoDemand.html?title=wcdbcs&k=E1yzuXJrg&videojjhost=videojj.com)

>IOS下载：1.5.0 （Build 26）
>
[http://fir.im/iwantvmango](http://fir.im/iwantvmango) 密码：videopls  

**热点位置：**
>有链接（有百科内链）`00：49`
有链接（有外链）`01：15`
>无链接`01：56`

**问题描述：**
>目前Web端和移动端对于云图热点的跳转逻辑不统一，辛苦@Mancy1011 @summernini 进行确认

### 点播
>有链接（百科内链）：视频播放时，点击云图后打开百科，**云图不消失**，视频暂停
有链接（外链）：视频播放时，点击云图后打开外链，**云图不消失**，返回视频暂停
无链接：视频播放时，点击云图无效，**云图不消失**，视频暂停

### 直播
>有链接（百科内链）：视频播放时，点击云图后打开百科，**云图不消失**，视频继续播放
有链接（外链）：视频播放时，点击云图后打开外链，**云图不消失**，返回视频继续播放
无链接：视频播放时，点击云图无效，**云图不消失**，视频继续播放

### IOS
>有链接（百科内链）：视频播放时，点击云图后打开百科，**云图消失**，视频继续播放
有链接（外链）：视频播放时，点击云图后打开外链，**云图消失**，返回视频继续播放
无链接：**未实现（按需求）**

### Android
>有链接（百科内链）：视频播放时，点击云图后打开百科，**云图消失**，**视频播放**
有链接（外链）：视频播放时，点击云图后打开外链，**云图消失**，视频暂停
无链接：**未实现**，点击后视频右侧滑出空的加载中的窗口

**Comment by summernini** [comment]
请按以下需求测试，谢谢~
## 点播
### Web
>有链接（百科内链）：视频播放时，点击云图后打开百科，**云图消失**，视频暂停
有链接（外链）：视频播放时，点击云图后打开外链，**云图不消失**，视频暂停
无链接：视频播放时，点击云图无效，**云图不消失**，视频暂停

### 移动IOS
>有链接（百科内链）：视频播放时，点击云图后百科侧栏滑出，**云图消失**，视频暂停
有链接（外链）：视频播放时，点击云图后打开外链，**云图不消失**，视频暂停
无链接：视频播放时，点击云图无效，**云图不消失**，视频暂停

### 移动Android
>同IOS

## 直播
### Web
>有链接（百科内链）：视频播放时，点击云图后百科侧栏滑出，**云图消失**，视频播放
有链接（外链）：视频播放时，点击云图后打开外链，**云图不消失**，视频播放
无链接：视频播放时，点击云图无效，**云图不消失**，视频播放

### 移动端（IOS & Android）
>有链接（百科内链）：视频播放时，点击云图后百科侧栏滑出，**云图消失**，视频播放
有链接（外链）：视频播放时，点击云图后打开外链，**云图不消失**，视频播放
无链接：视频播放时，点击云图无效，**云图不消失**，视频播放

**Comment by shixiaoyanjj** [comment]
测试结果已出，需按流程提交开发完成后送测，谢谢

**Comment by summernini** [comment]
@androidlgf @Zard1096 请按我写的需求修改

**Comment by hzzhujf** [comment]
经过讨论，统一做成点了消失

**Comment by Zard1096** [comment]
统一消失,外链必填
iOS端无需修改

**Comment by shixiaoyanjj** [comment]
# 测试结果：
## Web
### 点播
>- [ ] 有链接（百科内链）：视频播放时，点击云图后打开百科，**云图消失**，视频暂停
- [ ] 有链接（外链）：视频播放时，点击云图后打开外链，**云图消失**，返回视频暂停
- [ ] 无链接：外链必填 需控制台实现 #706

### 直播
>- [ ] 有链接（百科内链）：视频播放时，点击云图后打开百科，**云图消失**，视频播放
- [ ] 有链接（外链）：视频播放时，点击云图后打开外链，**云图消失**，返回视频继续播放
- [ ] 无链接：外链必填 需控制台实现 #706

## 移动（点播&直播）
### IOS
>- [ ] 有链接（百科内链）：视频播放时，点击云图后打开百科，**云图消失**，视频播放
- [ ] 有链接（外链）：视频播放时，点击云图后打开外链，**云图消失**，返回视频播放或暂停
- [ ] 无链接：外链必填 需控制台实现 #706

### Android
>- [ ] 有链接（百科内链）：视频播放时，点击云图后打开百科，**云图消失**，视频播放
- [ ] 有链接（外链）：视频播放时，点击云图后打开外链，**云图消失**，返回视频播放或暂停
- [ ] 无链接：外链必填 需控制台实现 #706

**Comment by summernini** [comment]
无连接：外链必填，需控制台实现，大侠新建了Issues #850

**Comment by bpceee** [comment]
@summernini 这个issue和我有啥关系。。？是不是可以关了。。
