### ISSUE TITLE
cytron web端第一期TODO

### ISSUE THREAD

**Issue by zhenkunou** [Venvy-dev/demand#977]
前端地址：
http://z-tron.cn/play/cytron/test-server.html 
控制台地址：
http://test-06.videojj.com/console/ 
前端信息层UI参考：
http://ryanluanfan.wix.com/videopls#!zerler/z2c8d

----

前端信息层提测：
----
- [x] 云链到百科
- [x] 云链到商品
- [x] 云链到广告信息
- [x] 云链到混合信息
- [x] 基本的云图
- [x] 卡牌游戏
- [x] 投票云窗
- [x] 云窗内的点赞
- [x] 口令红包
- [x] 播放器插入白点
- [x] 已经集成videojj监控api

前端打点提测：
----
- [x] 切换编辑、播放模式
- [x] 添加、删除百科tag
- [x] 添加、删除商品tag
- [x] 添加、删除广告信息tag
- [x] 添加、删除混合信息tag
- [x] 添加、删除云图
- [x] 添加、删除卡牌游戏
- [x] 添加、删除投票
- [x] 添加、删除口令红包
- [x] tag，云图，卡牌，投票图标修改位置
- [x] 云图，卡牌修改大小

待完成：
----
- [x] 隐性点云链
- [x] 打点的时候，节点拖动到视频边缘，文字超出视频的bug
- [x] tag跟踪框
- [ ] 集成第3方监控api
- [x] cytron销毁的方法
- [x] 其他登陆用户前端打点审核权限功能
- [ ] 一些浏览器兼容bugs修复
- [ ] console模块控制
- [ ] 前端打点交互优化（需要产品经理和ui配合）

**Comment by lihaiye** [comment]
- [ ] 打点时选择**云链到商品投票**提示：获取资源失败，发生未知错误（后台无对应资源）

**Comment by shixiaoyanjj** [comment]
## 1.编辑模式
- [ ] 1.1、云链标题输入2个字符提示：数据不完整，请重新输入，建议优化提示信息
- [ ] 1.2、未配置栏目的资源，在编辑时未显示在项目资源中，只显示在栏目资源

## 2.播放模式
- [ ] 2.1、广告：点击显示详情，外链无法打开
- [ ] 2.2、混合广告，点赞未区分导航页面

## 3.需要确认的功能
- [ ] 3.1、卡牌标题即卡牌热点图片标签，确认是否分别编辑更灵活
- [ ] 3.2、打开过的卡牌视频拖回不再出现，确认此逻辑是否满足产品需求
- [ ] 3.3、建议打开第一和第二张卡牌时，点击“还有X张卡牌”按钮可以关闭信息层，同右上角关闭按钮功能
- [ ] 3.4、混合广告的广告贴图显示和外链的不符合现在正式环境的资源配置，待确认
- [ ] 3.5、应用管理的主色调功能

**Comment by zhenkunou** [comment]
### 6月21日更新
@lihaiye
修复：`1.1`, `1.3`, `1.4`

**Comment by zhenkunou** [comment]
### 6月22日更新

新的提测： 
- tag到屏幕边缘的时候，文字被遮盖的bug

修复了 @lihaiye ：
- 1.7、打点界面的口令红包，由于包含了口令红包和优惠券红包，建议名称修改为红包
- 1.8、添加口令红包界面，节点名称显示为：广告投票信息
- 1.9、添加基本投票界面，节点名称显示为：基本样式云图
-  2.2. 打开广告、百科、混合信息层，还未进行点赞时，就已显示当前点赞总数量

修复了 @shixiaoyanjj ：
- 2.1、广告信息层点击显示详情，外链无法打开

**Comment by lihaiye** [comment]
### 6月22日测试更新：
- 打点的时候，节点拖动到视频边缘，文字超出视频的bug--**PASSED**
- 1.5、1.6、1.7、1.8、1.9、2.2问题--**PASSED**
- 2.1、1.3问题--**PASSED**

### 新增问题：
- [ ] 添加云图时，选择显示标题并且输入标题提交后，输入的标题未生效，始终显示原资源标题

**Comment by zhenkunou** [comment]
### 6月23日更新

修复了 @shixiaoyanjj ：
- 1.1 云链标题输入2个字符提示：数据不完整，请重新输入，建议优化提示信息
- 1.4 确认打点时，未判断资源有没有选择

修复了 @lihaiye ：
- 添加云图时，选择显示标题并且输入标题提交后，输入的标题未生效，始终显示原资源标题

**Comment by zhenkunou** [comment]
###6月24日更新

新的提测 @lihaiye @shixiaoyanjj ：
-  隐性点云链
-  其他登陆用户前端打点审核权限功能

修复了 @shixiaoyanjj ：
-  3.4、混合广告的广告贴图显示和外链的不符合现在正式环境的资源配置

**Comment by zhenkunou** [comment]
### 6月28日更新

新的提测 @lihaiye @shixiaoyanjj 
- 打点的时候标记是否跟踪

修复了 @shixiaoyanjj 
- 2.2、混合广告信息层点赞未区分导航页面

**Comment by zhenkunou** [comment]
### 6月30日更新

新的提测 @lihaiye @shixiaoyanjj 
- tag跟踪框

修复了 @lihaiye 
- 2.4. 添加隐链时，使用了自定义ICON以及特效和配色，隐链也会显示对应效果
- 2.5. 追加了轨迹的隐链，移动至视频左侧时，标题显示溢出视频范围 image

修复了 @shixiaoyanjj 
- 3.7. 混合广告无信息层的导航轮播功能
- 3.8. 百科无信息层图片的轮播功能
- 1.6. 热点图标大于一行时，和功能按钮重叠，建议增加滚动显示图标的功能 image

**Comment by zhenkunou** [comment]
第一期结束，剩下的请转移到第二期
https://github.com/Venvy-dev/demand/issues/1016

**Comment by zhenkunou** [comment]
ref #1115
