### ISSUE TITLE
灵眸产品化V1.0 & 1.1

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#990]
### 相关排期见下：
![1](https://cloud.githubusercontent.com/assets/17739064/16227974/abff851e-37e6-11e6-80b3-066029772f39.png)

### 人员分配：
产品：蘑菇
后端开发：刘聪
前端开发：帅斌
测试：测试团队

### 设计稿最终版麻烦稍后 @Mancy1011 传上来。

**Comment by Mancy1011** [comment]
> 20160622 最终设计稿
http://yx.tech.videojj.com/LingmoutoB_videoanalytics_web_20160622/

**Comment by summernini** [comment]
测试地址：http://test01.videojj.com/lingmou/

**Comment by Mancy1011** [comment]
20160701 
1.1更新：视频分析结果增加品牌、物体
http://yx.tech.videojj.com/LingmoutoB_videoanalytics_web_20160701

**Comment by Mancy1011** [comment]
**20160715更新**
**原型地址：**
http://yx.tech.videojj.com/Mushroom/LingmoutoB_videoanalytics_web_20160715

**1.1更新内容：**
* 增加标签功能
* 可选择视频分析的类型
* 增加文件夹管理功能
* 增加未读提醒功能
* 视频分析列表排版优化
* 视频列表分析类型 icon
* 视频分析类型增加品牌和物品
* 优化人物分析结果
* 添加视频时可选择文件夹
* 视频分析结果分步式查看
* 追加视频分析
* 视频分析完成邮件/短信提醒

**Comment by summernini** [comment]
![1](https://cloud.githubusercontent.com/assets/17739064/17199857/c396c3f2-54b2-11e6-9710-64860cdc83d2.png)
![2](https://cloud.githubusercontent.com/assets/17739064/17200273/59cf9b70-54b6-11e6-9567-2f4d8b234629.png)

**Comment by feizone** [comment]
@shixiaoyanjj 小乌龟灵眸1.1 的功能可以安排测试了
可以优先测试 列表页和添加页的功能
谢谢

**Comment by bug-cai** [comment]
- [ ] 1.添加标签限制未20个字，与原型表述不符。
![default](https://cloud.githubusercontent.com/assets/20593685/17400137/cfabd7b0-5a78-11e6-8e65-b43e173068ad.png)

- [ ] 2.视频分析列表右侧缺少新建文件夹选项。
![k97 se6 xj7u8 vt bztbw](https://cloud.githubusercontent.com/assets/20593685/17400144/da33e272-5a78-11e6-9cd4-a3b6d70b3dc2.png)
- [ ] 3.批量上传里，先操作选择文件夹后，则无法重新上传。
- [ ] 4.批量上传里， 点击重新上传后点击更多属性不弹出下拉框，且不可再上传文件。
- [ ] 5.批量上传后，在视频分析列表中，视频标题显示的是默认的视频标题，未显示文件名。
- [ ] 6.搜索只能首字符搜索，望改进为关键字搜索。
- [ ] 7.未读信息没有提醒。
- [ ] 8.鼠标hover视频列表，该列表未浮起，与原型表述不符。
- [ ] 9.分析类型显示不是原型里分析类型而是视频链接。
![k0 _p42 vttr im_y vub e](https://cloud.githubusercontent.com/assets/20593685/17400153/e91aa41a-5a78-11e6-867f-206b02f9374b.png)
- [ ] 10.编辑界面，缺少标签栏。
![n2s nil usr kzvmaeykdy0](https://cloud.githubusercontent.com/assets/20593685/17400160/f5b031a4-5a78-11e6-914d-1714fb75bca5.png)
- [ ] 11.移动到文件夹里的视频无法移动出来。
- [ ] 12.提示移动到文件夹里的视频无法移动出来后，会有选择一个视频不能进行视频移动的报错。
![e y8 9ve ezi0j yw](https://cloud.githubusercontent.com/assets/20593685/17400172/066af93e-5a79-11e6-988b-d05e1f7af2ab.png)
- [ ] 13.在所有状态下中进行筛选，文件夹不参与，且都显示最上层，望给出好的解决方案。
![yhf8_ rj 422a1cghqsc6](https://cloud.githubusercontent.com/assets/20593685/17400181/103bdd20-5a79-11e6-8e6a-8615857b15d2.png)
- [ ] 14.文件夹中的文件夹，未有返回上一层的交互，望改进。
- [ ] 15.可以考虑显示完整的路径
![hexqytw imrs zwn96lus c](https://cloud.githubusercontent.com/assets/20593685/17400196/2aefafca-5a79-11e6-9d3b-594b1afea56d.png)

**Comment by shixiaoyanjj** [comment]
@summernini @Mancy1011 
测试结果已更新，请安排修复后再次送测

**Comment by summernini** [comment]
@shixiaoyanjj 产品原型有更新，请 @Mancy1011 把最新的原型地址贴上来并且注明此次更新的具体内容。

**Comment by Mancy1011** [comment]
**20160808更新**
**原型地址：**
http://yx.tech.videojj.com/Mushroom/LingmoutoB_videoanalytics_web_20160808/#p=版本说明

**1.1版本新增功能：**
* 导航栏增加概览页（不可点击）
* 增加数据沙盘页（包含追加分析）
* 导航栏“视频分析列表”改为“分析管理”

**Comment by virgoone** [comment]
已提交测试[http://test.lm.videojj.com/lingmou](http://test.lm.videojj.com/lingmou) 

完成：

分析详情页面

**Comment by shixiaoyanjj** [comment]
- [ ] 21.选择文件夹中显示不存在的文件夹名称
![image](https://cloud.githubusercontent.com/assets/16204026/17519194/81a14dee-5e7d-11e6-84c7-c290ca22b641.png)

- [ ] 22.未选择分析类型添加失败的提示错误
![image](https://cloud.githubusercontent.com/assets/16204026/17519896/679ec72a-5e80-11e6-93dc-dd1294f28373.png)

- [ ] 23.分析类型多选，添加视频后，视频分析列表只显示靠前的一种类型
![image](https://cloud.githubusercontent.com/assets/16204026/17520149/334623b4-5e81-11e6-8712-5c599a0a4590.png)

- [ ] 24.点击新建文件夹后无法取消，鼠标点击任意位置都会新建成功
![image](https://cloud.githubusercontent.com/assets/16204026/17520222/78974cf4-5e81-11e6-8ab9-3cea94c7df20.png)

- [ ] 25.打开文件夹内的视频分析详情页面后，无法返回上层文件夹（没有路径）

- [ ] 26.视频分析详情页面没有品牌分析类型

- [ ] 27.在文件夹中搜索视频，会返回到最上层

**Comment by bug-cai** [comment]
- [ ] 29.当无权限账号登陆后，继续提示快速登陆，登陆时有无添加权限说明，且点击开启视频分析跳转如下的test-02页面。
![image](https://cloud.githubusercontent.com/assets/20593685/17577769/46717928-5fb4-11e6-95f5-8a70bd7bdc1c.png)
- [ ] 30.表述确认 @Mancy1011 添加时为明星，列表里显示对应为人脸是否可行。关于视频类型，原型里是视频管理，而设计稿是视频类型。
![image](https://cloud.githubusercontent.com/assets/20593685/17577870/30265200-5fb5-11e6-8a9f-2ca5e7599756.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 31.筛选状态，无满足筛选条件的视频所在文件夹未隐藏
（建议：应判断文件夹中是否有满足条件的视频，如果数量大于0则显示，如果为0则隐藏整个文件夹）
![image](https://cloud.githubusercontent.com/assets/16204026/17577487/ebb90490-5fb0-11e6-9ce2-51e700963bb5.png)

**Comment by lihaiye** [comment]
- [ ] 移动文件时，勾选文件后，再将勾去除，选择文件夹后也提示移动成功
- [ ] 移动文件时，可选择移动到原本的文件夹下【建议无法移动提示：无法将文件移动到自身目录下】

**Comment by summernini** [comment]
- [ ] 左侧树状按钮选中后颜色变灰，请调整颜色强度，现在是点击上去变化很浅看不清楚 @virgoone

**Comment by lihaiye** [comment]
### 其他建议： @Mancy1011 

1、移动文件的功能太繁琐，建议可以参考以下[百度云盘]
![image](https://cloud.githubusercontent.com/assets/17242849/17578182/706335ec-5fb8-11e6-99c5-103bf8546201.png)
![image](https://cloud.githubusercontent.com/assets/17242849/17578186/7abd6102-5fb8-11e6-88e9-97b7989819dd.png)

2、新建文件夹在视频类型当中操作，让人不易理解，建议单独开一个按钮
![image](https://cloud.githubusercontent.com/assets/17242849/17578190/88959272-5fb8-11e6-9f0c-73613837d6b4.png)

3、打开文件夹时，文件夹列表建议与文件夹列表路径显示的位置 放一起 ，如下
![image](https://cloud.githubusercontent.com/assets/17242849/17578219/c178dcd4-5fb8-11e6-8ccb-53f525ebe6bb.png)

4、打开文件夹时，上一级可点击的文件夹 鼠标hover时建议有下划线可点击效果，如下
![image](https://cloud.githubusercontent.com/assets/17242849/17578231/f1a7154c-5fb8-11e6-8b21-08761b214c5a.png)

**Comment by Mancy1011** [comment]
@lihaiye 
谢谢小叶子的建议~豆豆已经更新了UI，包含了以上问题的解决方案，其他部分也会慢慢完善
![Uploading 屏幕快照 2016-08-11 上午11.53.34.png…]()

**Comment by Mancy1011** [comment]
20160811更新
原型地址：
http://yx.tech.videojj.com/Mushroom/LingmoutoB_videoanalytics_web_20160811/

1.1版本新增功能：

* 去掉URL上传视频功能，改为通过上传文件添加分析视频
* 禁用批量上传功能，提供申请接口

**Comment by bug-cai** [comment]
##  bug修复情况更新
- [ ] 31、筛选状态，无满足筛选条件的视频所在文件夹未隐藏、 **应判断文件夹中是否有满足条件的视频**，如果数量大于0则显示，如果为0则隐藏整个文件夹，而不是完全去掉文件夹 
- [ ]  34.滚动页面，标题栏保持首行显示，但是在末尾是，未首行显示
- [ ] 48.视频分析列表，筛选或搜索后无法重置列表 ，就是点击分析管理和全部视频无反应，建议点击分析管理按钮实现此功能
- [ ] 编辑标签，点击某个标签删除后，点击取消，逻辑上应该是不被删除的，但标签仍被删除，需刷新页面才重现。

**Comment by bug-cai** [comment]
# 未修复bug整理
- [ ] 2.添加视频，选择文件夹右侧缺少新建文件夹选项。
**和聪沟通，新建文件夹功能本次不开发，为优化需求**
- [ ] 6.搜索只能首字符搜索，望改进为关键字搜索。**考虑到索引使用的性能问题，这里暂时只提供最左匹配，这期暂时不做全文检索**
- [ ] 7.未读信息没有提醒**未读信息：分析完成且没有进行任何操作的视频**
- [ ] 15.可以考虑显示完整的路径**文件夹路径由聪和帅兵沟通，选择开发最简便合理的方案**  
- [ ] 18.鼠标Hover状态选择位置，多次点击后状态名称不显示**这是原来选的materialUI框架本身的问题，这版无法解决，会在下版迭代一个UI框架**
- [ ] 20.视频列表右上角的按钮点击无效**本期迭代未开发卡片式，因此只保留列表式按钮** 
- [ ] 24.点击新建文件夹后无法取消，鼠标点击任意位置都会新建成功**蘑菇【新建文件夹的交互的确是这么设计的，没有问题】** 
- [ ] 28.视频达到多少数量后需要翻页？**--蘑菇【24个】**
- [ ] 32.批量上传，上传ANSI编码的csv文件后视频列表的中文显示乱码  **目前版本修改下载的csv文件后保存，必须用txt打开另存为UTF-8编码上传，视频列表才能正确显示中文**
- [ ] 37.视频分析，视频标题，分析类型，标签，提交时间无法完整显示
建议缩放页面时自动换行 

**一般逻辑是超出以省略号表示**

若按照省略号显示时，自适应上（1366*768 ）格式上也会出现问题，鼠标hover省略号时没显示完整的信息，用户无法通过省略号了解到完整信息，望优化或者提出其他解决方案。
![image](https://cloud.githubusercontent.com/assets/20593685/17692667/929fab72-63cd-11e6-811e-485074567c60.png)
- [ ] 40.不需要用户确定和取消的提示建议只显示关闭按钮
- [ ] 45.移动文件时，可选择移动到原本的文件夹下【建议无法移动提示：无法将文件移动到自身目录下】
- [ ] 46.已完成分析的视频，分析详情页面—品牌识别页：一直显示一个loading的状态
- [ ] 49.状态选择正在分析或分析完成时，点击新建文件夹无效且没有提示
- [ ] 50.新建文件夹时，点击文件夹名称位置后 创建面板消失，未新建成功
- [ ] 51.编辑标签，点击某个标签删除后，点击取消，逻辑上应该是不被删除的，但标签仍被删除，需刷新页面才重现。
- [ ] 52、文件夹是否可以移动 @Mancy1011 是按照提示上的可以移动文件夹，还是文件夹不能移动，修改提示信息。

![image](https://cloud.githubusercontent.com/assets/20593685/17692371/156f8f4c-63cc-11e6-8e5f-c36e782c7749.png)

**Comment by shixiaoyanjj** [comment]
## 剩余需要修复的BUG

- [ ] 31.筛选状态，不判断筛选结果隐藏所有文件夹 
**建议判断文件夹中是否有满足条件的视频**
如果数量大于0则显示，如果为0则隐藏整个文件夹

- [ ] 37.视频分析，视频标题，分析类型，标签，提交时间无法完整显示
建议缩放页面时自动换行 

>**一般逻辑是超出以省略号表示**

若按照省略号显示时，自适应上（1366*768 ）格式上也会出现问题，鼠标hover省略号时没显示完整的信息，用户无法通过省略号了解到完整信息，望优化或者提出其他解决方案。
![image](https://cloud.githubusercontent.com/assets/20593685/17692667/929fab72-63cd-11e6-811e-485074567c60.png)

- [ ] 40.不需要用户确定和取消的提示建议只显示关闭按钮

- [ ] 45.移动文件时，可选择移动到原本的文件夹下
【建议无法移动提示：无法将文件移动到自身目录下】

- [ ] 46.已完成分析的视频，分析详情页面—品牌识别页：一直显示一个loading的状态

- [ ] 49.状态选择正在分析或分析完成时，点击新建文件夹无效且没有提示，需要解决方案@Mancy1011 

- [ ] 50.新建文件夹时，点击文件夹名称位置后创建面板消失，未新建成功

- [ ] 51.编辑标签，点击某个标签删除后，点击取消，逻辑上应该是不被删除的，但标签仍被删除，需刷新页面才重现。

- [ ] 52.文件夹是否可以移动
@Mancy1011 是按照提示上的可以移动文件夹，还是文件夹不能移动，修改提示信息。
![image](https://cloud.githubusercontent.com/assets/20593685/17692371/156f8f4c-63cc-11e6-8e5f-c36e782c7749.png)

- [ ] 53.视频达到24个后未翻页

**Comment by shixiaoyanjj** [comment]
@summernini @Mancy1011 灵眸最新测试结果已更新，请评估和修复后再提交测试验证，谢谢

**Comment by Mancy1011** [comment]
31.筛选状态，不判断筛选结果隐藏所有文件夹 
**文件夹不参与筛选，只判断当前文件夹里的视频**

37.视频分析，视频标题，分析类型，标签，提交时间无法完整显示
**hover标签显示全部内容，视频时间只显示日期，待实现**

40.不需要用户确定和取消的提示建议只显示关闭按钮
**目前修改UI控件太费时，下次版本迭代更换UI框架后会避免这样的问题**

45.移动文件时，可选择移动到原本的文件夹下
**将文件移动到原本文件夹下没有问题，不是bug**

46.已完成分析的视频，分析详情页面—品牌识别页：一直显示一个loading的状态
**已修复的bug**

49.状态选择正在分析或分析完成时，点击新建文件夹无效且没有提示
**列表状态不应该影响新建文件夹，待修复 **

50.新建文件夹时，点击文件夹名称位置后创建面板消失，未新建成功
**点击文件夹名称位置应该是移动光标，不取消或确认新建，待修复**
 
51.编辑标签，点击某个标签删除后，点击取消，逻辑上应该是不被删除的，但标签仍被删除，需刷新页面才重现
**bug，待修复**

52.文件夹是否可以移动
**文件夹可以移动，待实现**

53.视频达到24个后未翻页
**经沟通，列表不翻页，该需求不做（参考百度云盘）**

**Comment by bug-cai** [comment]
# 复测结果
## 测试通过
31、46、49、51

## 测试未通过
- [ ] 37、hover标签显示全部内容，以实现，但是未hover时省略号后面会显示残框

![ik54esxb 5adu3jal 2 vps](https://cloud.githubusercontent.com/assets/20593685/17731239/13a82178-649f-11e6-960e-f5901ef3cad7.png)
52、 @Mancy1011 确认一下文件夹的移动规则
- [ ] （1）母文件夹能移动到自己的子文件夹中，且确认后整个母文件夹（包括子文件）在列表中消失，应规避此操作。
- [ ] （2）列表下创建同名文件夹，创建失败，直接创建如下图所示的文件夹，出现此类操作前，是否需要提示。
![image](https://cloud.githubusercontent.com/assets/20593685/17731647/aec66240-64a0-11e6-9366-7c9c27efe697.png)
- [ ] （3）同名文件夹能通过移动文件夹的方法，在同一个列表中，同时出现。
![vhw51 t64 zwofgfc5 q8](https://cloud.githubusercontent.com/assets/20593685/17731250/1ffba742-649f-11e6-92c0-f16117317451.png)

**Comment by shixiaoyanjj** [comment]
## 测试建议 @Mancy1011 
1、建议在视频信息内保留视频上传时的名称
2、建议在视频信息内显示视频时间


## 新增BUG
1、视频修改：添加视频播放地址后删除，剩余一个视频播放地址时，减号未即时清除
![image](https://cloud.githubusercontent.com/assets/16204026/17765335/c4d37cb4-6557-11e6-8d9c-02c72b4bbb7e.png)

2、视频修改：标签栏不显示名称‘标签’

3、视频修改：视频名称为空时，不能确定修改，但没有校验提示

**Comment by shixiaoyanjj** [comment]
灵眸新原型见 #1124 灵眸1.2
此issues关闭
